CHARACTERS = [
    "Alter",
    "Ash",
    "Ballistic",
    "Bangalore",
    "Bloodhound",
    "Catalyst",
    "Caustic",
    "Conduit",
    "Crypto",
    "Fuse",
    "Gibraltar",
    "Horizon",
    "Lifeline",
    "Loba",
    "Mad Maggie",
    "Mirage",
    "Newcastle",
    "Octane",
    "Pathfinder",
    "Rampart",
    "Revenant",
    "Seer",
    "Valkyrie",
    "Vantage",
    "Wattson",
    "Wraith",
]
WEAPONS = [
    "HAVOC Rifle",
    "VK-47 Flatline",
    "Hemlok Burst AR",
    "R-301 Carbine",
    "Nemesis Burst AR",
    "Alternator SMG",
    "Prowler Burst PDW",
    "R-99 SMG",
    "Volt SMG",
    "C.A.R. SMG",
    "Devotion LMG",
    "L-STAR EMG",
    "M600 Spitfire",
    "Rampage LMG",
    "G7 Scout",
    "Triple Take",
    "30-30 Repeater",
    "Bocek Compound Bow",
    "Charge Rifle",
    "Longbow DMR",
    "Kraber .50-Cal Sniper",
    "Sentinel",
    "EVA-8 Auto",
    "Mastiff Shotgun",
    "Mozambique Shotgun",
    "Peacekeeper",
    "RE-45 Auto",
    "P2020",
    "Wingman",
]

PLATFORMS = [
    "PC",
    "PS4",
    "PS5",
    "Xbox One",
    "Nintendo Switch",
    "Xbox Series X/S",
    "Android",
    "iOS",
]
