import asyncio

import websockets

# Generated by protoc
from events_pb2 import ObserverSwitched, Player
from team_data import custom_team_name

WEBSOCKET_HOST = "localhost"
WEBSOCKET_PORT = 7777


async def update_team_name(websocket, path):
    print("Connected!")

    async for message in websocket:
        try:
            incoming = ObserverSwitched()
            incoming.ParseFromString(message)

            target_player: Player = incoming.target
            team_id: int = target_player.teamId
            team_name: str = custom_team_name.get(team_id, "Unknown")

            await websocket.send(team_name)
            print(f"Observer switched to Team {team_id}: {team_name}")

        except Exception as e:
            print(message)
            print(e)


async def main():
    async with websockets.serve(update_team_name, WEBSOCKET_HOST, WEBSOCKET_PORT):
        print(f"Serving on {WEBSOCKET_HOST}:{WEBSOCKET_PORT}...")
        await asyncio.Future()


asyncio.run(main())
